// A paced local UI rehearsal. Dwell periods allow delivery of the narration;
// elapsed time is not represented as application latency or a human usability trial.
import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve('../..');const dir=path.join(root,'verification/product');
fs.mkdirSync(dir,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const blocked=[];await context.route('**/*',route=>{if(new URL(route.request().url()).hostname==='127.0.0.1')return route.continue();blocked.push(route.request().url());return route.abort('internetdisconnected');});
const page=await context.newPage();const start=performance.now();const steps=[];
async function step(at,name,narration,action){const left=at*1000-(performance.now()-start);if(left>0)await new Promise(r=>setTimeout(r,left));await action();steps.push({name,narration,observed_at_seconds:Number(((performance.now()-start)/1000).toFixed(3)),result:'PASS'});console.log(name);}
try{
 await step(0,'Search','CivicProof asks what the records can establish. This local demonstration contains five historical Nigerian road dossiers. Search Umuahia; matching sections remain separate.',async()=>{await page.goto('http://127.0.0.1:3000/');await page.locator('#search').fill('Umuahia');await page.locator('.result').first().waitFor();});
 await step(18,'Open C01','Open Section I, contract 6208. The dossier is a historical evidence investigation, not a current condition report.',async()=>{await page.locator('a[href="/projects/C01/"]').click();await page.locator('.dimension').first().waitFor();});
 await step(34,'Five dimensions','Appropriation is supported for the schedule proposition. Award and implementation are incomplete. Procurement and payment remain unverifiable. These are five questions about evidence, not a verified end-to-end lifecycle.',async()=>{await page.locator('#dimensions').scrollIntoViewIfNeeded();});
 await step(55,'Provenance','The schedule records the 2019 annual amount. The drawer preserves its institution, page 653, source field and raw value. The schedule is not independently authenticated as the final signed legal instrument.',async()=>{await page.getByRole('button',{name:'View evidence',exact:true}).first().click();await page.getByRole('dialog').waitFor();});
 await step(76,'Financial distinctions','Annual appropriation, historical contract sum and certified amount have different meanings. The report records forty-four percent progress, but the observation date is unknown. Neither value establishes present-day condition.',async()=>{await page.getByRole('button',{name:'Close evidence drawer'}).click();await page.locator('#records').scrollIntoViewIfNeeded();});
 await step(96,'Payment question','The answer does not establish an independently verified treasury payment. Certified amount remains certification, not payment.',async()=>{await page.getByRole('button',{name:'What payment evidence is available?',exact:true}).click();await page.locator('#answer-payment').scrollIntoViewIfNeeded();});
 await step(111,'Completion question','The factual completion proposition remains unverifiable. Historical reported progress does not establish that the project was completed.',async()=>{await page.getByRole('button',{name:'Was this project completed?',exact:true}).click();await page.locator('#answer-completed').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(dir,'fixed-answer.png')});});
 await step(127,'C09 unresolved route','C09 shares contract number 6063 with a Works record, but the routes materially differ. The record remains a possible match; its contractor, money and progress do not fill accepted project findings.',async()=>{await page.goto('http://127.0.0.1:3000/projects/C09/');await page.locator('#candidates').waitFor();await page.locator('#candidates').scrollIntoViewIfNeeded();});
 await step(149,'C12 competing and excluded evidence','C12 retains both procurement candidates. Their amounts are not selected or summed. A milestone describing Owo–Ifon–Sobe remains excluded. The undated transaction has unresolved identity and no named payee; it is not verified treasury payment.',async()=>{await page.goto('http://127.0.0.1:3000/projects/C12/');await page.locator('#excluded').waitFor();await page.locator('#excluded').scrollIntoViewIfNeeded();});
 await step(176,'Export','The verification download is the exact artifact behind this page. It retains every evidence state, candidate, exclusion and qualification. Uncertainty survives into the product.',async()=>{const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download verification JSON'}).click();const download=await pending;await download.saveAs(path.join(dir,'demo-C12.verification.json'));if(!fs.readFileSync(path.join(dir,'demo-C12.verification.json')).equals(fs.readFileSync(path.join(root,'data/artifacts/C12.json'))))throw Error('Export mismatch');await page.screenshot({path:path.join(dir,'export.png')});});
 const elapsed=(performance.now()-start)/1000;
 fs.writeFileSync(path.join(root,'verification/golden-path.json'),JSON.stringify({status:'PASS',method:'Automated paced UI rehearsal with explicit narration dwell time; not a human usability study or latency benchmark',elapsed_seconds:elapsed,target_seconds:[120,240],within_target:elapsed>=120&&elapsed<=240,external_network:'All non-loopback browser requests blocked throughout',blocked_requests:blocked,fixture_mutations:0,steps},null,2));
}catch(error){fs.writeFileSync(path.join(root,'verification/golden-path.json'),JSON.stringify({status:'FAIL',error:String(error),steps},null,2));throw error;}finally{await browser.close();}
